spring.application.name=catalog-service
server.port=8081
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cafe_catalog?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
cafe.jwt.secret=${CAFE_JWT_SECRET:}
cafe.permission.url=${PERMISSION_SERVICE_URL:http://localhost:8083}
cafe.catalog.url=${CATALOG_SERVICE_URL:http://localhost:8081}
server.error.include-message=always
spring.jackson.time-zone=Asia/Ho_Chi_Minh
server.address=127.0.0.1
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
debug=false
cafe.auth.url=${AUTH_SERVICE_URL:http://localhost:8080}
